name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create TypeScript declaration file
        run: |
          mkdir -p src/@types
          echo 'declare module "qrcode";' > src/@types/qrcode.d.ts

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Create next.config.js with correct configuration for custom domain
        run: |
          cat > next.config.js << 'EOL'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            // basePath and assetPrefix are NOT needed for custom domains on GitHub Pages
            // basePath: process.env.NODE_ENV === 'production' ? '/coinaddress' : '',
            // assetPrefix: process.env.NODE_ENV === 'production' ? '/coinaddress/' : '',
            images: {
              unoptimized: true,
            },
            trailingSlash: true,
          };
          
          module.exports = nextConfig;
          EOL

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Add .nojekyll file and CNAME
        run: |
          touch out/.nojekyll
          echo "coinaddress.io" > out/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true