name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create TypeScript declaration file
        run: |
          mkdir -p src/@types
          echo 'declare module "qrcode";' > src/@types/qrcode.d.ts

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      # Copy the exact CSS from the working Manus version
      - name: Copy CSS from working version
        run: |
          # Download the CSS from the working Manus version
          curl -o src/app/globals.css https://czctwcvo.manus.space/_next/static/css/74b95eaa14662645.css
          
          # Add the original imports back at the top
          sed -i '1s/^/@import url("https:\/\/fonts.googleapis.com\/css2?family=Montserrat:wght@400;500;600;700;800&family=Poppins:wght@300;400;500;600;700&display=swap");\n\n@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n/' src/app/globals.css

      # Use a simple next.config.js without basePath for custom domain
      - name: Create next.config.js with correct configuration for custom domain
        run: |
          cat > next.config.js << 'EOL'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            images: {
              unoptimized: true,
            },
            trailingSlash: true,
          };
          
          module.exports = nextConfig;
          EOL

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Add .nojekyll file and CNAME
        run: |
          touch out/.nojekyll
          echo "coinaddress.io" > out/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true