name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create TypeScript declaration file
        run: |
          mkdir -p src/@types
          echo 'declare module "qrcode";' > src/@types/qrcode.d.ts

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      # Fix Tailwind CSS configuration to use direct variables
      - name: Fix Tailwind CSS configuration
        run: |
          # Update tailwind.config.ts to use direct color values instead of HSL
          cat > tailwind.config.ts << 'EOL'
          import type { Config } from "tailwindcss";

          export default {
            darkMode: ["class"],
            content: [
              "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
              "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
              "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
            ],
            theme: {
              extend: {
                colors: {
                  background: 'var(--background)',
                  foreground: 'var(--text-primary)',
                  card: {
                    DEFAULT: 'var(--card-bg)',
                    foreground: 'var(--text-primary)'
                  },
                  popover: {
                    DEFAULT: 'var(--card-bg)',
                    foreground: 'var(--text-primary)'
                  },
                  primary: {
                    DEFAULT: 'var(--primary)',
                    foreground: 'white'
                  },
                  secondary: {
                    DEFAULT: 'var(--secondary)',
                    foreground: 'white'
                  },
                  muted: {
                    DEFAULT: 'var(--border)',
                    foreground: 'var(--text-secondary)'
                  },
                  accent: {
                    DEFAULT: 'var(--primary-light)',
                    foreground: 'var(--text-primary)'
                  },
                  destructive: {
                    DEFAULT: 'var(--error)',
                    foreground: 'white'
                  },
                  border: 'var(--border)',
                  input: 'var(--border)',
                  ring: 'var(--border-focus)',
                },
                borderRadius: {
                  lg: 'var(--radius)',
                  md: 'calc(var(--radius) - 2px)',
                  sm: 'calc(var(--radius) - 4px)'
                },
                keyframes: {
                  'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' }
                  },
                  'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' }
                  }
                },
                animation: {
                  'accordion-down': 'accordion-down 0.2s ease-out',
                  'accordion-up': 'accordion-up 0.2s ease-out'
                }
              }
            },
            plugins: [require("tailwindcss-animate")],
          } satisfies Config;
          EOL

      # Use a simple next.config.js without basePath for custom domain
      - name: Create next.config.js with correct configuration for custom domain
        run: |
          cat > next.config.js << 'EOL'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            images: {
              unoptimized: true,
            },
            trailingSlash: true,
          };
          
          module.exports = nextConfig;
          EOL

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Add .nojekyll file and CNAME
        run: |
          touch out/.nojekyll
          echo "coinaddress.io" > out/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true